### PR TITLE
Re-add new tooltip component

### PR DESCRIPTION
**Pull request by xhluca**
This is an updated attempt for: https://github.com/plotly/dash-core-components/pull/940

Note #941 was also added to this PR in https://github.com/plotly/dash-core-components/pull/982/commits/6a18fd9845e510b669aae06c87f0bacda3bbed49

Related: 
* https://github.com/plotly/plotly.js/pull/5512
* https://github.com/plotly/dash-docs/pull/1104

TODOs for demo:
- [x] Image example that uses URLs
- [x] Image example that reads images from file system and base64 encodes them
- [x] Clientside callback example with URLs
- [x] Example with loading state and a time.sleep(1) to simulate a long running callback
- [x] Serverside callback example with a nicely formatted tooltip made with HTML and inline CSS with a little box shadow,  similar to the style of the nytimes:
- [x] Clientside callback example of ^

### CODE REVIEW

**Comment by alexcjohnson** [comment]
@xhlulu please drop package-lock.json from this PR, since you aren't updating package.json. If you do change package.json, note that dash core is now using node 16 / npm 7

**Comment by xhluca** [comment]
> @xhlulu please drop package-lock.json from this PR, since you aren't updating package.json. If you do change package.json, note that dash core is now using node 16 / npm 7

Sure. I removed the commit that added `package-lock.json` and did a force push

**Comment by xhluca** [comment]
@alexcjohnson am I supposed to commit `NAMESPACE` changes as well?

**Comment by xhluca** [comment]
@alexcjohnson I feel this PR is ready for review.  A few questions for review:

- any idea why the 27 tests are failing? are we still supporting 2.7?
- What name should I give it? It's currently called `dcc.AbsoluteTooltip` but i'm certain there's a better name than this.

**Comment by alexcjohnson** [comment]
Closing - will remake shortly in the monorepo

**Pull request closed without merging**
