### PR TITLE
Dash Tabs component

### PR DESCRIPTION
**Pull request by chriddyp**

### CODE REVIEW

**Comment by chriddyp** [comment]
tabs

**Comment by chriddyp** [comment]
Fixes https://github.com/plotly/dash/issues/36

**Comment by chriddyp** [comment]
Try it out on the pre-release channel with 
```
pip install dash-core-components==0.13.0-rc4
```

That example above:
```python
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
from loremipsum import get_sentences

app = dash.Dash()

app.scripts.config.serve_locally = True

app.layout = html.Div([
    dcc.Tabs(
        tabs=[
            {'label': 'Tab {}'.format(i), 'value': i} for i in range(1, 5)
        ],
        value=3,
        id='tabs'
    ),
    html.Div(id='tab-output')
], style={
    'width': '80%',
    'fontFamily': 'Sans-Serif',
    'margin-left': 'auto',
    'margin-right': 'auto'
})


@app.callback(Output('tab-output', 'children'), [Input('tabs', 'value')])
def display_content(value):
    data = [
        {
            'x': [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
                  2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012],
            'y': [219, 146, 112, 127, 124, 180, 236, 207, 236, 263,
                  350, 430, 474, 526, 488, 537, 500, 439],
            'name': 'Rest of world',
            'marker': {
                'color': 'rgb(55, 83, 109)'
            },
            'type': ['bar', 'scatter', 'box'][int(value) % 3]
        },
        {
            'x': [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
                  2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012],
            'y': [16, 13, 10, 11, 28, 37, 43, 55, 56, 88, 105, 156, 270,
                  299, 340, 403, 549, 499],
            'name': 'China',
            'marker': {
                'color': 'rgb(26, 118, 255)'
            },
            'type': ['bar', 'scatter', 'box'][int(value) % 3]
        }
    ]

    return html.Div([
        dcc.Graph(
            id='graph',
            figure={
                'data': data,
                'layout': {
                    'margin': {
                        'l': 30,
                        'r': 0,
                        'b': 30,
                        't': 0
                    },
                    'legend': {'x': 0, 'y': 1}
                }
            }
        ),
        html.Div(' '.join(get_sentences(10)))
    ])


if __name__ == '__main__':
    app.run_server(debug=True)

```

**Comment by chriddyp** [comment]
Vertical view
tabs-vertical

**Comment by TheoLvs** [comment]
Awesome ! Thank you very much

**Comment by richard-muir** [comment]
Hey Chris, looking great! Tabs & Upload have taken Dash to the next level!

How did you get the tabs on the left-hand side? Had a look through the source, but struggling to figure it out.

**Comment by chriddyp** [comment]
@richard-muir Sorry about that! I forgot to publish my latest commits.
Here is the latest example:
```
pip install dash-core-components==0.13.0-rc5
pip install loremipsum
```

```python
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
from loremipsum import get_sentences

app = dash.Dash()

app.scripts.config.serve_locally = True

vertical = True

if not vertical:
    app.layout = html.Div([
        dcc.Tabs(
            tabs=[
                {'label': 'Market Value', 'value': 1},
                {'label': 'Usage Over Time', 'value': 2},
                {'label': 'Predictions', 'value': 3},
                {'label': 'Target Pricing', 'value': 4},
            ],
            value=3,
            id='tabs',
            vertical=vertical
        ),
        html.Div(id='tab-output')
    ], style={
        'width': '80%',
        'fontFamily': 'Sans-Serif',
        'margin-left': 'auto',
        'margin-right': 'auto'
    })

else:
    app.layout = html.Div([
        html.Div(
            dcc.Tabs(
                tabs=[
                    {'label': 'Market Value', 'value': 1},
                    {'label': 'Usage Over Time', 'value': 2},
                    {'label': 'Predictions', 'value': 3},
                    {'label': 'Target Pricing', 'value': 4},
                ],
                value=3,
                id='tabs',
                vertical=vertical,
                style={
                    'height': '100vh',
                    'borderRight': 'thin lightgrey solid',
                    'textAlign': 'left'
                }
            ),
            style={'width': '20%', 'float': 'left'}
        ),
        html.Div(
            html.Div(id='tab-output'),
            style={'width': '80%', 'float': 'right'}
        )
    ], style={
        'fontFamily': 'Sans-Serif',
        'margin-left': 'auto',
        'margin-right': 'auto',
    })


@app.callback(Output('tab-output', 'children'), [Input('tabs', 'value')])
def display_content(value):
    data = [
        {
            'x': [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
                  2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012],
            'y': [219, 146, 112, 127, 124, 180, 236, 207, 236, 263,
                  350, 430, 474, 526, 488, 537, 500, 439],
            'name': 'Rest of world',
            'marker': {
                'color': 'rgb(55, 83, 109)'
            },
            'type': ['bar', 'scatter', 'box'][int(value) % 3]
        },
        {
            'x': [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
                  2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012],
            'y': [16, 13, 10, 11, 28, 37, 43, 55, 56, 88, 105, 156, 270,
                  299, 340, 403, 549, 499],
            'name': 'China',
            'marker': {
                'color': 'rgb(26, 118, 255)'
            },
            'type': ['bar', 'scatter', 'box'][int(value) % 3]
        }
    ]

    return html.Div([
        dcc.Graph(
            id='graph',
            figure={
                'data': data,
                'layout': {
                    'margin': {
                        'l': 30,
                        'r': 0,
                        'b': 30,
                        't': 0
                    },
                    'legend': {'x': 0, 'y': 1}
                }
            }
        ),
        html.Div(' '.join(get_sentences(10)))
    ])


if __name__ == '__main__':
    app.run_server(debug=True)

```

**Comment by dotsdl** [comment]
Awesome @chriddyp! This is really going to make some incredible things possible with relatively little effort.

**Comment by chriddyp** [comment]
I have pushed `v0.13.0rc8` to include the fixes from `v0.12.7`

**Comment by Izzatbir** [comment]
Hey @chriddyp ,
This pull seems to have distorted the dcc.datePickeRange function somehow. It is showing weirdly large arrow between date ranges.

**Comment by chriddyp** [comment]
I have rebased this branch off of the latest version. Try this out with `pip install dash-core-components==0.15.0rc1`

**Comment by mtreu** [comment]
This looks awesome! However, is there a way to change background-color of each tab?

**Comment by mtreu** [comment]
This looks awesome? However, is there a way to change the color of a tab?

**Comment by jbrav** [comment]
Hey, @chriddyp thank you very much. I am trying to actually get different data on each tab. I am quite new in Python, but so far I have tried the following.

`import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
from loremipsum import get_sentences

app = dash.Dash()

app.scripts.config.serve_locally = True





app.layout = html.Div([
    dcc.Tabs(
        tabs=[
            {'label': 'Tab {}'.format(i), 'value': i} for i in range(1, 4)
        ],
        value=4,
        id='tabs',
    ),
    html.Div(id='tab-output')
], style={
    'width': '80%',
    'fontFamily': 'Sans-Serif',
    'margin-left': 'auto',
    'margin-right': 'auto'
})


@app.callback(Output('tab-output', 'children'), [Input('tabs', 'value')])
def display_content(value):
    data = [
        {
            'x': [1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017],
            'y': [42, 41, 64, 54, 12, 54, 69, 12, 76, 35, 68,86, 56, 57, 65, 43, 91,85,12, 59, 76, 14, 16, 28, 40, 56, 52, 78,75, 67, 12, 52, 75, 43, 52, 54, 64, 62, 68],
            'name': 'Schroders',
            'marker': {
                'color': 'rgb(54, 82, 110)'
            },
            'type': ['bar', 'scatter'][int(value) % 2]
        },
        {
            'x': [1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017],
            'y': [52, 51, 74, 64, 22, 44, 59, 32, 16, 65, 18,16, 16, 27, 35, 13, 11,25,72, 19, 96, 64, 96, 68, 10, 96, 82, 18,25, 37, 72, 12, 25, 13, 32, 14, 24, 12, 98],
            'name': 'MSF ',
            'marker': {
                'color': 'rgb(26, 118, 255)'
            },
            'type': ['bar', 'scatter'][int(value) % 2]
        },
        {
            'x': [1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017],
            'y': [32, 11, 84, 94, 62, 14, 79, 52, 16, 15, 98,26, 36, 47, 15, 83, 31,45,22, 69, 16, 74, 46, 98, 70, 16, 22, 38,45, 17, 42, 22, 35, 83, 72, 44, 94, 22, 60],
            'name': 'OMS',
            'marker': {
                'color': 'rgb(55, 83, 109)'
            },
            'type': ['bar', 'scatter'][int(value) % 2]
        },
    ],
def muestra_contenido(value):
    data1 = [
            {
                'x': [1940, 1950, 1960, 1970],
                'y': [1, 2, 3, 4],
                'name': 'test1',
                'marker': {
                'color': 'rgb(60, 41, 200)'
                },
                'type': ['bar', 'scatter'][int(value)%2]
         },
         {
                'x': [1940, 1950, 1960, 1970],
                'y': [5, 6, 7, 8],
                'name': 'test2',
                'marker': {
                'color': 'rgb(61, 42, 201)'
            },
                'type': ['bar', 'scatter'][int(value)%2]
        }
    ],
    return html.Div [(
        dcc.Graph(
            id='graph',
            figure={
                'data': data,
                'layout': {
                    'margin': {
                        'l': 30,
                        'r': 0,
                        'b': 30,
                        't': 0
                    },
                    'legend': {'x': 0, 'y': 1}
                }
            }
        ),
        html.Div('Estoy haciendo una prueba para ver como funcionaria esto')
    )],
    return html.Div([
        dcc.Graph(
            id='graph1',
                figure={
                'data': data1,
                'layout': {
                    'margin': {
                        'l': 30,
                        'r': 0,
                        'b': 30,
                        't': 0
                    },
                    'legend': {'x': 0, 'y': 1}
                }
            }
        ),
        html.Div('Estoy haciendo una prueba para ver como funcionaria esto')
    ])

if __name__ == '__main__':
    app.run_server(debug=True)`

I would love if you could point where my error is. I have also tried to create another label, without success as it is apparent .

**Comment by chriddyp** [comment]
@jbrav - Would you mind asking this implementation question in the dash community forum? https://community.plot.ly/c/dash. That'll keep things a little bit more organized for me and you're likely to get more people to help you out there. Thanks!

**Comment by salvatoregiannuzzi** [comment]
Hi Chris, thanks for Dash, it's amazing!
I've installed the dash-core-components 0.15.2 (together with the html-components) but it seems that the Tabs component is missing in the package. Is there something that I could have missed?

Thank you!

**Comment by radumas** [comment]
I noticed a thing that happens on mobile if the tabs don't contain the same number of lines at narrower resolutions, that the "selected tab" line comes down to the shorter tab's height instead of maintaining an unbroken top border for the tabs component. We personally find this behaviour undesirable.

image

Minimal example

```python
from dash import Dash
import dash_core_components as dcc
import dash_html_components as html


app = Dash()

app.layout = html.Div(dcc.Tabs(tabs=[{'label': '123456789 More-text', 'value': 1},
                   {'label': '1234567890A More-text', 'value': 2}],
             value=1,
             id='tabs',
             style={'font-weight':'bold'}))

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by Akronix** [comment]
Hi @salvatoregiannuzzi @radumas.

I've customized and improved the Tabs component from what @chriddyp made and included it in our [Dash components suite](https://github.com/Grasia/grasia-dash-components).
I've been using it for a while and we're currently using tabs for [our own project](https://github.com/Grasia/wikichron), which is currently in alpha release.

Our tabs allows icons as well as icon + text or only text as labels. Eventually we plan to support the feature of adding and closing tabs (a dynamically number of tabs)

I encourage you to try out our suite, at least meanwhile Dash' apps gets officially supported.
That's the reason I developed our "fork". We don't earn anything more than your feedback from your experience. Issues and pull requests are welcome.

Our suite is available in pipy, so to use just do: `pip install grasia-dash-components`.

@radumas I've tried your example using our version of Tabs and I couldn't reproduce your issue. I've deployed it on heroku, so you can check it: https://test-grasia-dash-components.herokuapp.com/ 

Please, let me know if everything looks ok. (Code is [here](https://github.com/Akronix/test_grasia_dash_components) and is almost the same you posted as an example)

**Comment by radumas** [comment]
@chriddyp Are there Python versions for which this won't install? One of my team couldn't install with `Python 3.6.1`

**Comment by pthakur4** [comment]
Hi, I have installed the dash-core-components version 0.15.2, but unable to find Tabs component in the dash-core-components package. Kindly help, dash has been very helpful, but want to push some of my charts on tabs. Also when I use it in my code - while running it gives me error.

dcc.Tabs(
AttributeError: module 'dash_core_components' has no attribute 'Tabs'

See below code - 

>>> import dash_core_components as dcc
>>> print(dcc.__version__)
0.15.2
>>> dir(dcc)
['Checklist', 'DatePickerRange', 'DatePickerSingle', 'Dropdown', 'Graph', 'Input
', 'Interval', 'Link', 'Location', 'Markdown', 'RadioItems', 'RangeSlider', 'Sli
der', 'SyntaxHighlighter', 'Textarea', 'Upload', '__builtins__', '__cached__', '
__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__sp
ec__', '__version__', '_components', '_css_dist', '_current_path', '_dash', '_js
_dist', '_os', '_sys', '_this_module', 'component', 'version']
>>>

**Comment by chriddyp** [comment]
> Hi, I have installed the dash-core-components version 0.15.2, but unable to find Tabs component in the dash-core-components package.

@pthakur4 This feature has not been merged yet. See the previous comment https://github.com/plotly/dash-core-components/pull/74/#issuecomment-341588771

**Comment by alastairbegley** [comment]
Would it be possible to rebase this off a more recent release?

**Comment by ploncker** [comment]
Is there anyway to put a background image in tab?

**Comment by Akronix** [comment]
@ploncker There is using the attribute 'icon' in our custom implementation of Dash Tabs in [grasia-dash-components](https://github.com/Grasia/grasia-dash-components).
Simply, install it trough pip with `pip install grasia-dash-components` and follow the examples.
Let me know if you get stuck or you run into a problem.

**Comment by alastairbegley** [comment]
@Akronix I can’t get your version of the tabs components to work if they are dynamically displayed as a result of a callback.

**Comment by Akronix** [comment]
@alastairbegley please, open an issue and attach some example code here: https://github.com/Grasia/grasia-dash-components/issues

**Comment by ColasDroin** [comment]
> Would it be possible to rebase this off a more recent release?
Same here, I've started an app which incorporates both polar charts and tabs, this would be really useful.
Cheers!

**Comment by yellowbean** [comment]
Cool !

**Comment by charleyferrari** [comment]
@chriddyp Do you think there's a way for `dcc`s within tabs to remain active even if the tab isn't selected? 

Here's a toy example of what I'm thinking:

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(__name__, static_folder='assets')
server = app.server
app.scripts.config.serve_locally=True
app.css.config.serve_locally=True
app.config['suppress_callback_exceptions']=True

app.layout = html.Div([
    dcc.Tabs(tabs = [
        {'label': 'Tab 1', 'value': 1},
        {'label': 'Tab 2', 'value': 2}
    ], id='tabs', value = 1),
    html.Div([], id='tab_output'),
    html.Div([], id='output')
])

@app.callback(
    Output('tab_output', 'children'),
    [Input('tabs', 'value')]
)
def show_dropdowns(value):
    if value == 1:
        return dcc.Dropdown(options = [
            {'label': 'A', 'value': 'A'},
            {'label': 'B', 'value': 'B'}
        ], id='dropdown1', value = 'A')
    if value == 2:
        return dcc.Dropdown(options = [
            {'label': 'C', 'value': 'C'},
            {'label': 'D', 'value': 'D'}
        ], id='dropdown2', value = 'C')

@app.callback(
    Output('output', 'children'),
    [Input('dropdown1', 'value'), Input('dropdown2', 'value')]
)
def format_text(d1, d2):
    return 'Your first dropdown says {} and your second dropdown says {}'.format(d1, d2)

if __name__ == '__main__':
    app.run_server(debug=True)
```

Ideally I'd like a user to be able to make selections in each tab, and have the main output draw from both tabs.

Something like this doesn't work now because the tabs change the layout, and it's impossible for both `dcc`s to exist at the same time.

**Comment by chriddyp** [comment]
@charleyferrari - All of the inputs of a callback need to be visible in the layout at the same time in order for them to fire the callback. You could keep them layout by just toggling the visibility, like:
```python
app.layout = html.Div([
     dcc.Tabs(...),
     dcc.Dropdown(id='dropdown1', style={'display': 'none'}, ...)
     dcc.Dropdown(id='dropdown2', style={'display': 'none'}, ...)
])
@app.callback(Output('dropdown1', 'style'), [Input('tabs', 'value')])
def update_dropdown(value):
    return {'display': 'block' if value == 1 else 'none'}

@app.callback(Output('dropdown2', 'style'), [Input('tabs', 'value')])
def update_dropdown(value):
    return {'display': 'block' if value == 2 else 'none'}
```

**Comment by Antoniofiliona** [comment]
@chriddyp Hey i've been trying to make use of tabs to change out the layout in dash by making dropdown visible/insivisble but your example code that makes a callback output to 'styles' failes in the following manner.

```
@app.callback(    dash.dependencies.Output('field', 'style'), [dash.dependencies.Input('tabs', 'value')])
def set_field_visibility(tab):
    return [{'display' : 'inline-block' if tab >1  else 'none'}]

>>>NonExistantPropException: 
Attempting to assign a callback with
the property "style" but the component
"field" doesn't have "style" as a property.
Here is a list of the available properties in "dropdown1":
['id', 'options', 'value', 'className', 'clearable', 'disabled', 'multi', 'placeholder', 'searchable']
```

Is there another way or will controlling the styling from a callback something that we'll be able to do in the near future?
Thanks!

**Comment by nite** [comment]
@chriddyp is there a rc including this after `dash-core-components==0.22.1 `? Your last install above was `pip install dash-core-components==0.13.0-rc5`

**Comment by steremma** [comment]
This is an extremely useful PR, congrats @chriddyp ! Can we maybe have a (rough) estimation of when this could be merged? I am interested in using it for a client facing application so I would feel a lot better using master!

**Comment by QCTW** [comment]
Thanks for the great work.

I encountered one problem when I tried to an upload component (https://dash.plot.ly/dash-core-components/upload) inside a tab, it can not properly display the upload block. If I don't put the upload component (the same codes) in the tab, it is working fine...

Is this normal?

**Comment by brainbutcher** [comment]
Hi Chris,
I am using the tabs in the vertical=True mode. (see screen shot) Why is my tab background color not extending past the original screen size - on the scroll down?
Is this a bug? Or, am I doing something wrong? I love the tabs addition, but without this background-color-extension on the scroll-down it makes it look un-professional.
Can you help?
Best regards,
~BB 

image

image

**Comment by jen0liu** [comment]
@chriddyp for Tabs, it's not included in the latest release (0.22). I had to revert back to an older version 0.15.rc01 which means I can't use some other new cool features people added to dash-core-component. Can you please see if you can merge to the latest branch? Thanks.

**Comment by tmjrbea** [comment]
If it can be merged that would be great since scattermapbox doesn't work with this branch and I love the tabs way too much.

**Comment by randiaz95** [comment]
Major firepower with this tab pre release, the programming gods are happy :).

**Comment by kyleabeauchamp** [comment]
I too am interested in seeing this PR updated for the latest release.

**Comment by chriddyp** [comment]
Thank you everyone so much for the reviews and feedback ❤️ 

We have incorporated this feedback into a new revision of the Tabs component here: https://github.com/plotly/dash-core-components/pull/213.

**Comment by jogendraKhalsa** [comment]
Hi Chris, ... can you help with a situation wherein i have to update real time using dcc.Interval as component-Interval is not part of 0.21.0rcxx .
Thanks in Advance.

**Pull request closed without merging**
