### PR TITLE
Bump Plotly.js to v1.58.0

### PR DESCRIPTION
**Pull request by archmoj**
Similar to #875.

@Marc-Andre-Rivet 
Here are some TODOs:
 - please update CHANGELOG in respect to https://github.com/plotly/plotly.js/releases/tag/v1.58.0 
 - please check if you get the same diff for `package-lock.json`?
 - watch out as it is my very first PR to this repo.
Thanks!

cc: @nicolaskruchten @alexcjohnson

### CODE REVIEW

**Comment by Marc-Andre-Rivet** [comment]
@archmoj 

> please check if you get the same diff for package-lock.json?

Looks good. Assuming you've run `npm ci` followed by `npm install --save --exact plotly.js@1.5.8.0`

**Comment by archmoj** [comment]
> @archmoj
> 
> > please check if you get the same diff for package-lock.json?
> 
> Looks good. Assuming you've run `npm ci` followed by `npm install --save --exact plotly.js@1.5.8.0`

No. I run `npm i`.

**Comment by Marc-Andre-Rivet** [comment]
> No. I run npm i.

@archmoj 😮 - Revalidated, I get the same result as you if I run `npm ci` + bump Plotly.js locally so the lockfile in this PR is 👌 but I don't understand why. If I run `npm i` + bump Plotly.js I get additional changes.

Maybe this has to do with `npm==6.14.9` in your environment. Will investigate a bit. But this PR is ready to be merged in any case.

**Review by Marc-Andre-Rivet — APPROVED** [review]
💃 @archmoj Thanks!

**Comment by archmoj** [comment]
Some of the strange diffs in `package-lock` was related to different version of `tape`.

`plotly.js`
plotlyjs

`dash-core`
dashcore

Should we do something about it?

**Comment by Marc-Andre-Rivet** [comment]
@archmoj I've always seen many nested deps being updated here but never thought much it, just assumed they are coming from Plotly.js or one of its deps - that said we consume the built Plotly.js package so differences here should have no impact.

If `tape` is a direct dependency of Plotly.js using the exact version might help for consistency, but this inconsistency should have no impact based on usage.

**Comment by archmoj** [comment]
> @archmoj I've always seen many nested deps being updated here but never thought much it, just assumed they are coming from Plotly.js or one of its deps - that said we consume the built Plotly.js package so differences here should have no impact.
> 
> If `<named_dep>` is a direct dependency of Plotly.js using the exact version might help for consistency, but this inconsistency should have no impact based on our usage.

We used to change various dependencies in the past but not quite this time.
Concerning `tape` module I have this PR open: https://github.com/mikolalysenko/boundary-cells/pull/1
@alexcjohnson could you please ping Mikola there?

**Comment by alexcjohnson** [comment]
Heh ok, @archmoj thanks for nailing down where those packages come from. Would be nice to clean up at some point (and yes, I'll nudge Mikola re: tape) but for now this seems fine. 💃

**Comment by archmoj** [comment]
@Marc-Andre-Rivet 
I am not authorized to merge this pull request.
Please merge it when you want.

**Comment by Marc-Andre-Rivet** [comment]
@archmoj I'll update the branch policy to allow `core-contributors` to merge in core repos. Current policy is arguably a bit too strict since it's already protected by mandatory codeowners review.

**Comment by archmoj** [comment]
> @archmoj I'll update the branch policy to allow `core-contributors` to merge in core repos. Current policy is arguably a bit too strict since it's already protected by mandatory codeowners review.

"strict" is good.

**Comment by Marc-Andre-Rivet** [comment]
@archmoj But too strict isn't always :)

**Pull request merged**
