### PR TITLE
Add current date's initial visible month

### PR DESCRIPTION
**Pull request by xblad**
Added current date as the last resort for the initialVisibleMonth property of the component in DatePickerRange.react.js and in DatePickerSingle.react.js (issue #115)

### CODE REVIEW

**Comment by chriddyp** [comment]
Thanks! This looks good to me. A few other things would be helpful:
- Would you mind adding a test? We can just render the component and then take a screenshot of the new behaviour. 
- Would you mind updating the `CHANGELOG.md` and the version numbers in `version.py` and `package.json`?

**Comment by xblad** [comment]
@chriddyp, I have added the tests and updated version number (_v0.22.3_ + _tag_).
Nevertheless, it is my first contribution on Github, so quick revision of the changes is highly appreciated 😃 
Btw, I see, that **percy/dash-core-components** test was failed, but I don't have an access to the resource, so I'm not able to check why...

**Comment by valentijnnieman** [comment]
@chriddyp This seems solid - can we update & merge this? 💃

**Comment by mikesmith1611** [comment]
It looks like change has been implemented:
https://dash.plot.ly/dash-core-components/datepickersingle
can confirm it works

**Pull request closed without merging**
