### PR TITLE
upgrade plotly.js to 1.39.1

### PR DESCRIPTION
**Pull request by chriddyp**
@plotly/dash please review

### CODE REVIEW

**Comment by valentijnnieman** [comment]
💃 Looks good!

**Comment by leejt489** [comment]
@chriddyp I was trying to pull in plotly 1.39.0 to see if it solved issue https://github.com/plotly/dash/issues/223. I just locally changed `__init__.py` https://github.com/plotly/dash-core-components/blob/16515bb2279e11102f39f46781cde26b5de8c3f7/dash_core_components/__init__.py#L26 to use version 1.39.0 for the `external_url`, which looked like the only thing you changed apart from downloading the new JS file and updating the `relative_package_path` and the version number. Everything deployed fine, but I started getting a new JavaScript error when the map is rendering:

Uncaught ReferenceError: t is not defined
(anonymous) @ blob:http://127.0.0.1:8050/d7192aea-f3a0-4f37-baf9-b238ca89d2b4:1
(anonymous) @ blob:http://127.0.0.1:8050/d7192aea-f3a0-4f37-baf9-b238ca89d2b4:1

I was able to produce this error on your example https://github.com/plotly/dash-recipes/blob/master/dash-plotly-132-histogram-map.py. I only commented out line 10 so as to use the external script.

Maybe this is just a local error for me as I was trying to get ahead of your release, but from what I can tell it seems likely this is a real issue. Maybe you want to take a look and ensure you don't get this error before pushing this new version?

**Comment by chriddyp** [comment]
Thanks for reporting @leejt489 ! I'll take a look before releasing

**Comment by leejt489** [comment]
@chriddyp  I'd hazard the guess that it's related to https://github.com/plotly/plotly.js/issues/2787

**Comment by leejt489** [comment]
Yep, definitely related to that issue. For the record, referencing plotly 1.39.0 did indeed fix https://github.com/plotly/dash/issues/223 ... just in time for my demo tomorrow :)

**Comment by etpinard** [comment]
Bumping to plotly.js@1.39.1 will fix https://github.com/plotly/dash-core-components/pull/228#issuecomment-403246518

**Comment by chriddyp** [comment]
Bumped up to 1.39.1

**Pull request merged**
