### PR TITLE
Added values as defaultProps in checklist

### PR DESCRIPTION
**Pull request by shreyasbapat**
Solves plotly/dash#239

### CODE REVIEW

**Comment by chriddyp** [comment]
This looks good! A few small things to take this across the finish line 🏁 
1. Create a screenshot test. 
- Create a new function in `test_integration`: `test_checklist_empty_values`
- Add a `self.snapshot('initial rendering of checklist')` - This'll take a screenshot of the app using the percy.io screenshot service
- Click on the checklist item programatically with a CSS selector. This'll be something like:
```
self.wait_for_element_by_css_selector('#checklist-container input')[0].click()
```
- Verify that the appropriate callback was fired with the appropriate value. To check that a callback was fired.
- Altogether, this test will look _something_ like:
```
from multiprocessing import Value

class Tests(IntegrationTests):
    # ... the other functions in the class

    def test_checklist(self):
        app = dash.Dash()

        app.layout = html.Div([
            dcc.Checklist(
                id='checklist',
                options=[
                    {'label': 'option 1', 'value': 'option-1'},
                    {'label': 'option 2', 'value': 'option-2'},
                    {'label': 'option 3', 'value': 'option-3'},
                ]
            ),
            html.Div(id='output')
        ])
        
        call_count = Value('i', 0)

        @app.callback(Output('output', 'children'),
                      [Input('checklist', 'values')])
        def update_output(value):
            call_count.value = call_count.value + 1
            return str(value)

        self.startServer(app)

        # check initial text
        wait_for_text_to_equal('output', 'None')

        self.snapshot('initial rendering of checklist')

        # click on the value
        self.wait_for_element_by_css_selector(
            '#checklist-container input')[0].click()

        # check the output text
        wait_for_text_to_equal('output', '[option-1]')

        # check that the callback was fired twice
        self.assertEqual(call_count.value, 2)

        self.snapshot('second rendering of checklist')
```
3. Bump the version in `version.py` and the `version` field in `package.json` and add an entry in the `CHANGELOG.md`. This is technically a bug fix, so we'll go from `0.22.1` to `0.22.2` (see https://semver.org/)
4. Tag me for another review!

Let us know if you have the time to make this changes. If not, perhaps another community member can take it up. And thanks again for your contribution and your time!

**Comment by shreyasbapat** [comment]
Yeah, I will make these changes tomorrow only! Thanks!

**Comment by shreyasbapat** [comment]
@chriddyp  Can you guide me a bit why this is happening? https://circleci.com/gh/plotly/dash-core-components/595?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by bpostlethwaite** [comment]
@shreyasbapat I can take a look at this PR and see if I can get those tests running for you. I'll update this thread once Percy is generating snapshots we can look at.

**Comment by shreyasbapat** [comment]
@bpostlethwaite  Actually, I am grateful that you said it, but I want to know the cause so that I fix it. As I am not very much aware with the codebase, If you just guide me a bit, I think I would be able to do it.

**Comment by bpostlethwaite** [comment]
Ok great, here are a couple clues from my investigation yesterday

- dcc.Checkbox works fine when you supply a values field
- dcc.Checkbox breaks when you add the values field which seems to break JSON serialization. Trying to investigate it in the ipdb console leads to recursive errors.
- My next step was to inspect the generated code for Checkbox and step through the case where it no longer has a values field

Happy hunting!

**Comment by chriddyp** [comment]
Ugh, this sounds familiar: https://github.com/plotly/dash-core-components/issues/133#issuecomment-353641641

**Comment by bpostlethwaite** [comment]
Yep that is almost definitely the issue.

**Comment by shreyasbapat** [comment]
Thanks a lot @bpostlethwaite  ! :smile:  If I am unable to solve the problem in a day or two, I will ask your help!

**Comment by shreyasbapat** [comment]
Couldn't figure it out @bpostlethwaite ! Sorry for wasting time.

**Comment by bpostlethwaite** [comment]
Well given https://github.com/plotly/dash-core-components/issues/133#issuecomment-353641641 it seems like these are our choices:
A) rename "values" to some other prop name 
B) start messing around with the Base implementation of the Component
C) Disband PR and continue with a mandatory "values" prop

@chriddyp have you investigated any hijinx like whitelisting values in the Collections.MutableMapping implementation? We could sit another class on top that would do keyname delegation or monkey patch MutableMapping. 

`values` (and for that matter `keys`) are not exactly obscure prop names. Maybe I'll spend a little time on this today.

**Comment by bpostlethwaite** [comment]
It seems like `items`, `pop`, `popitem`, `clear`, `update`, and `setdefault` may be other reserved method/attribute names.

**Comment by shreyasbapat** [comment]
What can be the way to solve this?

**Comment by valentijnnieman** [comment]
I'm going to close this PR for now as it doesn't seem to be moving forward - feel free to reopen if you are still working on this!

**Pull request closed without merging**
