### PR TITLE
Serve unminified bundle support

### PR DESCRIPTION
**Pull request by T4rk1n**
Add `build:js-dev` command and support in `_js_dist`.

plotly/dash#369

### CODE REVIEW

**Comment by rmarren1** [comment]
:dancer: I had that percy issue before, I think it goes away when you rebase. Can you do that before merging to make sure?

**Comment by T4rk1n** [comment]
Renamed the bundles plotly/dash#384

**Comment by T4rk1n** [comment]
@valentijnnieman Can you look at the percy diff ? I rebased on master an hour ago and it looks like there is a regression in the tabs.

**Comment by valentijnnieman** [comment]
@T4rk1n Looks like the Graph is rendered differently with the new version of plotly.js, looks better to me :-)

**Comment by valentijnnieman** [comment]
@T4rk1n Percy is being a little bit difficult lately it seems... Feels like the snapshots are changing slightly every time it runs. Maybe if we replace the tests with the Selenium WaitAPI instead of the time.sleep() it will be more stable?

**Comment by T4rk1n** [comment]
@valentijnnieman Yea, I think you can go ahead with the Selenium WaitAPI if you have the time.

**Pull request merged**
