### PR TITLE
Insert style-loader loaded CSS at top of <head/>

### LINKED ISSUE #380: Update from 0.37.7 to 0.38.0 break local css for Dash components
**TL;DR:** `0.37.7 -> 0.38.0` breaks `dcc` css styling.
----
I have styled some `dcc` in a local `.css` file — e.g.:
```css
.Select-control {
  width: 100%;
  font-family: sans-serif;
  height: 50px;
  border-radius: 0;
  font-size: 100%;
}

.Select-placeholder,
.Select-value-label {
  line-height: 50px;
}

.DateRangePicker,
.DateRangePickerInput {
  display: block;
}

.DateInput {
  min-width: 110px;
  width: 45%;
  text-align: center;
}

.DateInput__display-text {
  font-family: sans-serif;
  font-weight: normal;
}

.DateRangePickerInput__arrow{
  width: 10%;
  min-width: 24px;
  text-align: center;
}

.Select-menu-outer{
  font-family: sans-serif;
}
```

The file is stored in my `asset` folder. It contains other style for other elements too.
When I upgraded from `0.37.2` to `0.38.0`, the css file is still loaded (other elements do get styled), however, `dcc` are not styled anymore:

`pip install -Iv dash-core-components==0.37.2`: **OK** (right dropdown size)
screenshot from 2018-11-13 15-31-26

`pip install -Iv dash-core-components==0.38.0`: **ERROR** (dropdowns are styled as default, despite css)
screenshot from 2018-11-13 15-31-04

### PR DESCRIPTION
**Pull request by valentijnnieman**
This fixes and closes #380 by inserting the default CSS loaded by `style-loader` at the top of `<head/>`, so that user loaded CSS will be below it, allowing users to overwrite the default CSS.

### CODE REVIEW

**Comment by chriddyp** [comment]
Could we add an integration test with percy here? Something that mimics the user code by supplying some CSS in the `assets/` folder that overrides a dash core component style.

**Comment by valentijnnieman** [comment]
@chriddyp Good point - I've added one. I tried to do some assertions on the CSS being set, but couldn't get it to work. The suggested `value_of_css_property()` returned incorrect values - `rgb(0,0,0)` for colors and `1184px` for widths - no matter what it was.

**Comment by valentijnnieman** [comment]
@chriddyp Is it working in the main `dash` repo? I see that in Dash there's a `test/assets` folder, https://github.com/plotly/dash/tree/master/tests/assets but I can't figure out how that's working / what the set up is.

**Comment by chriddyp** [comment]
>  Is it working in the main dash repo?

Not sure off the top of my head. You might be able to check out the Percy snapshots in that repo and see they look like they have custom css applied.

**Comment by chriddyp** [comment]
Also, looking at `git blame`, @T4rk1n was the last one to work in the `dash/tests/assets` folder, so he can help answer your questions about that part of the code

**Comment by T4rk1n** [comment]
Just tested and it doesn't load the assets in the dash tests percy snapshots.

**Comment by valentijnnieman** [comment]
> Just tested and it doesn't load the assets in the dash tests percy snapshots.

Ah too bad. Thanks for taking a look!

**Comment by T4rk1n** [comment]
But I got them to load with this config:

```
loader = percy.ResourceLoader(
            webdriver=cls.driver,
            base_url='/assets',
            root_dir='tests/assets'
        )
```

https://percy.io/plotly/dash/builds/1182426?utm_campaign=plotly&utm_content=dash&utm_source=github_status

**Comment by T4rk1n** [comment]
No only thing I see different is the root_dir is relative `'test/assets'`.

**Comment by T4rk1n** [comment]
Here you can see the whole changes:

https://github.com/plotly/dash/pull/461

**Comment by valentijnnieman** [comment]
@T4rk1n That was it - removing the root_static_dir suggested by the Percy docs and having the root_dir relative fixed it. Thanks for your help!

**Comment by T4rk1n** [comment]
Great, look like it worked :dancer:

You can review plotly/dash#461 while you are at it ?

**Pull request merged**
