### PR TITLE
Fix graph issues

### PR DESCRIPTION
**Pull request by chriddyp**
- should fix https://github.com/plotly/dash-docs/issues/81
- also adds a resize after first plot in case graphs aren’t sized up in their container

### CODE REVIEW

**Comment by chriddyp** [comment]
@mjkramer - If you're still around, would you mind elaborating on this comment? https://github.com/plotly/dash-core-components/issues/171#issuecomment-370213691 I'm essentially patching this with that suggestion but I'm forgetting what you meant by
> OK, previous "solution" is no bueno because it prevents the handlers from seeing the updated props. Now I see why bindEvents was being called repeatedly.

**Comment by chriddyp** [comment]
@plotly/dash or @plotly/frontend - could someone review?

**Comment by chriddyp** [comment]
@charleyferrari - could you check if this fixes the resizing issue that you saw in your latest dashboard project? try out the prerelease with
```
pip install dash-core-components==0.21.1rc2
```

**Comment by mjkramer** [comment]
Hi Chris. When `bindEvents` is only called once, don't those callbacks end up always seeing the `props` as they were at the time that `bindEvents` was called? Or is it irrelevant (i.e. do `clear_on_hover`, `setProps`, and `fireEvent` never change)? Why not, in addition to the `if (!this._hasPlotted)` fix, get rid of the `props` argument to `bindEvents`, and just let the callbacks access `this.props` directly? I do this in my components, and while I can't claim to fully understand what's going on under the hood, I haven't seen any issues.

**Comment by chriddyp** [comment]
thanks @mjkramer ! agreed, `this.props` should suffice here.

**Comment by chriddyp** [comment]
Fixes the issues in the docs https://github.com/plotly/dash-docs/issues/81
image

**Comment by nicolaskruchten** [comment]
The resize thing looks good to me!

**Comment by chriddyp** [comment]
Ping @charleyferrari re https://github.com/plotly/dash-core-components/pull/178#issuecomment-376387427

**Comment by charleyferrari** [comment]
@chriddyp working for me with Halliburton app:

hburt3

**Pull request merged**
