### PR TITLE
Add autoComplete prop to Dropdown #808

### PR DESCRIPTION
**Pull request by AnnMarieW**
Currently, the default for   `autoComplete` is `"on"` in the Dropdown component.  However, unlike in dcc.Input,  there is no `autoComplete`  prop to control this setting. 

When  `autoComplete="on"`, the browser will autocomplete fields that have ids like "name" or "address" based on the history stored in the browser. This blocks the options defined in the dropdown.

image

This pull request addresses https://github.com/plotly/dash-core-components/issues/808, https://github.com/plotly/dash/issues/960 and https://github.com/plotly/dash-core-components/issues/787
by setting the `autoComplete` default to `"off"` and adding the `autoComplete` prop

This issue has also been mentioned numerous times on the community forum:
https://community.plotly.com/t/disable-autocomplete-for-dropdowns-input-box-in-dash/22463
https://community.plotly.com/t/disable-browser-autocomplete-on-multiselect-dropdown/37478
https://community.plotly.com/t/keep-getting-autofill-for-dropdown-not-all-browsers/30359

I updated dropdown unit test to include the autoComplete prop, but I'm not sure if other tests are needed.

Here is a small app that will duplicate the issue - at least in Chrome.  

```
import dash
from dash.dependencies import Input, Output
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)
app.layout = html.Div(
    [
        dcc.Dropdown(
            id="name",
            options=[
                {"label": "New York City", "value": "NYC"},
                {"label": "Montreal", "value": "MTL"},
                {"label": "San Francisco", "value": "SF"},
            ],
            value="NYC",
           # autoComplete="on",  # or 'off'    new prop
        ),
        html.Div(id="output-div"),
    ]
)


@app.callback(Output("output-div", "children"), Input("name", "value"))
def update(city):
    return f"You have selected {city}"


if __name__ == "__main__":
    app.run_server(debug=True)

```

### CODE REVIEW

**Comment by chriddyp** [comment]
This looks good to me! @alexcjohnson - Any concerns or ideas of how we might test this?

**Comment by alexcjohnson** [comment]
Interesting... re: tests I think unit tests are sufficient, just mount a default element and ensure the `<input>` in the DOM has `autoComplete` disabled, then mount one with it explicitly turned on and ensure that this is propagated.

But I guess I wonder whether this even needs to be an option, or if we can get away with just disabling `autoComplete` here? Is there a real use case where you want the built-in browser completion with a dropdown? Isn't it always going to get in the way of the explicit dropdown items, and if you wanted autocomplete you'd use a `dcc.Input` instead? AFAICT all the people asking about this just want to be able to disable it, does anyone like it?

**Comment by AnnMarieW** [comment]
I think I saw a post where the autocomplete feature was being used with the Dropdown.  But right, they could just switch it to an dcc.Input for better results.  Do you want me to remove the prop?

**Comment by alexcjohnson** [comment]
I looked through the posts you referenced more carefully and still see nobody arguing they like this behavior. So yes, let's treat this as a bug and simply lock it to `autoComplete: 'off'`. If anyone comes back and complains we can always add the prop in later, with default `'off'` as you have now.

**Comment by AnnMarieW** [comment]
I think I saw it in a blog post or stackoverflow or something, but I can't find it now.    I'll take the prop out for now, and it will be easy to add back if  necessary.

**Pull request closed without merging**
