### PR TITLE
[MRG] Add basic textarea component

### PR DESCRIPTION
**Pull request by betatim**
This adds a basic `<textarea>` component. Mostly a straight copy of `<input>`.

Seems to work but the dev instructions in the README don't quite work for me (in terms of what I need to rerun when etc). However a small dash app that uses a textarea instead of an input works.

Should we add some more of the `wrap`, `rows`, `cols` properties? Anything else?

### CODE REVIEW

**Comment by chriddyp** [comment]
very nice! this looks good to me. I think we should add _all_ of the HTML attributes to `Input` and to `TextArea`. I do this programatically in `dash-html-components` and we could just copy and paste the output like from: https://github.com/plotly/dash-html-components/blob/master/src/components/Textarea.react.js#L30-L177

**Comment by chriddyp** [comment]
@betatim - I'm happy to wrap this up and add the rest of the properties if you'd like. Let me know!

**Comment by betatim** [comment]
I was going to add them either later tonight or tomorrow. If I don't feel free to merge.

**Comment by chriddyp** [comment]
looks good to me. thanks @betatim !!

**Comment by betatim** [comment]
:clinking_glasses: good to help out with a cool project :)

**Pull request merged**
